### PR TITLE
Fix for broken dialogs after opening the same one twice

### LINKED ISSUE #3638: Trying to open the dialog for the second time when it's already opened causes dialog cover to stay after dialog closing
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to [CDN](http://cdn.ckeditor.com/4.13.0/full-all/samples/)
2. Execute `CKEDITOR.instances.editor.execCommand( 'link' )` twice 
3. Close the dialog

### Expected result

Dialog is closed and editor is available

### Actual result

Dialog cover stays after closing dialog, editor is unavailable

## Other details

This behaviour was introduced in #2413. Before it was also broken, but in different way - after calling dialog for the second time it has been hiding behind cover.

* Browser: all
* OS: macOS
* CKEditor version: `4.13.0`
* Installed CKEditor plugins: `dialog`

### PR DESCRIPTION
**Pull request by Comandeer**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#3638](https://github.com/ckeditor/ckeditor4/issues/3638): Fixed: opening the same dialog twice causes it to become hidden under the dialog's page cover.
```

## What changes did you make?

I've just added a simple check if the current dialog (`CKEDITOR.dialog._.currentTop`) is the same as the one being opened. If it's the case, the positioning logic is skipped.

Additionally I've polished some tests to always close dialogs.

## Which issues does your PR resolve?

Closes #3638.

### CODE REVIEW

**Comment by sculpt0r** [comment]
Rebased on the newest master

File: tests/plugins/dialog/plugin.js [hunk 1]
```diff
@@ -81,6 +81,16 @@
 	bender.editor = {};
 
 	bender.test( {
+		tearDown: function() {
+			var dialog = CKEDITOR.dialog.getCurrent();
```
Comment (sculpt0r) [inline tests/plugins/dialog/plugin.js:85]: Since this tearDown looks the same as the one used in another test (`positioning`) and we already have `_helpers` for dialog tests, maybe we could move this code to a separate function with proper naming, like `hideAllDialogs`?

File: tests/plugins/dialog/positioning.js [hunk 2]
```diff
@@ -13,8 +13,11 @@
 		},
 		tearDown: function() {
 			var dialog = CKEDITOR.dialog.getCurrent();
-			if ( dialog ) {
+
+			while ( dialog ) {
```
Comment (sculpt0r) [inline tests/plugins/dialog/positioning.js:17]: Please take a look at comment to `tearDown` in `tests/plugins/dialog/plugins.js`

File: tests/plugins/dialog/positioning.js [hunk 3]
```diff
@@ -218,8 +221,39 @@
...
 
+			editorBot.dialog( 'link', function() {
+				editorBot.dialog( 'link', function( dialog ) {
+					var cover = CKEDITOR.document.findOne( '.cke_dialog_background_cover' ),
+						coverZIndex = parseInt( cover.getStyle( 'z-index' ), 10 ),
+						dialogZIndex = parseInt( dialog.getElement().getStyle( 'z-index' ), 10 );
+
+					dialog.getButton( 'cancel' ).click();
+
+					assert.isTrue( dialogZIndex > coverZIndex, 'Dialog should be above the cover' );
```
Comment (sculpt0r) [inline tests/plugins/dialog/positioning.js:238]: We don't have anything similar to [chai isAbove](https://www.chaijs.com/api/assert/#method_isabove), so maybe we could at least give both zIndexes values to the assert message? In case of fail there will be already some results visible besides `expected true but was false`.

File: plugins/dialog/plugin.js [hunk 4]
```diff
@@ -905,7 +905,8 @@ CKEDITOR.DIALOG_STATE_BUSY = 2;
 				CKEDITOR.dialog._.currentTop = this;
 				this._.parentDialog = null;
 				showCover( this._.editor );
-			} else {
+			} else if ( CKEDITOR.dialog._.currentTop !== this ) {
+				// Do the magic with z-indexes only if the current dialog is not already visible (#3638).
```
Comment (sculpt0r) [inline plugins/dialog/plugin.js:909]: I'm not 100% sure about this comment. I mean the part with zIndex. The entire `else...if` is prevented `if the current dialog is not already visible`. So besides zIndex operation we also have assignments to `parentDialog` and `currentTop`.

We could leave just the part with issue reference at the top, and move the zIndex part just before zIndex operation?

**Review by sculpt0r — CHANGES_REQUESTED** [review]
Looks good and working fine. Just a few small suggestions from me.

Also, I made a small fix for white characters in `hidingcover.md` test and rebased - so make sure you pull all updates.

**Comment by Comandeer** [comment]
I've updated tests according to the comments and slightly rephrase the comment inside the code – it should be more suitable now.

**Review by sculpt0r — APPROVED** [review]
LGTM :tada: 

Thank you for the corrections.

I made a single simple change myself: I bumped the CKEditor4 version in the manual test tag. Since the master branch is already frozen, we have no chance to release it with `4.16.1`.

Changelog added.

Waiting with merge till master will be available.

**Comment by sculpt0r** [comment]
Blocked merge by frozen master branch

**Comment by sculpt0r** [comment]
Rebased temporary on `next`.
