### PR TITLE
Fix for integration between Word and Easy Image

### LINKED ISSUE #4994: Pasted content from MS Word with enabled Easy Image is embedded
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open an [Easy Image sampe](https://ckeditor.com/docs/ckeditor4/latest/examples/easyimage.html)
1. Paste some text content from MS Word

### Expected result

Content is pasted as text.

### Actual result

Content is pasted as an embedded image.

https://user-images.githubusercontent.com/10279586/144389529-6d2ab73f-15ff-4bc5-8d1e-3b0bdb77e44e.mov

## Other details

We have some manual test coverage for PFW and Easy Image, so I assume that the issue could be caused by some browser upstream. The same use case works correctly in Firefox.

Similar bug report: https://github.com/ckeditor/ckeditor4/issues/4459

* Browser: Chrome Version 96.0.4664.55 (Official Build) (x86_64) on macOS
* CKEditor version: Starting from 4.9.0

### PR DESCRIPTION
**Pull request by Comandeer**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4994](https://github.com/ckeditor/ckeditor4/issues/4994): Fixed: content from Word is pasted as image when [Easy Image](https://ckeditor.com/cke4/addon/easyimage) plugin is enabled.
```

## What changes did you make?

The issue was connected with how `imagebase` plugin handles pasting to the editor. It simply checked if there are any files inside clipboard data. However, Word includes a screenshot of the content alongside content in text format, resulting in pasting the image. Switching to [`CKEDITOR.plugins.clipboard.dataTransfer#isFileTransfer()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_clipboard_dataTransfer.html#method-isFileTransfer) seems to do the trick.

## Which issues does your PR resolve?

Closes #4994.

### CODE REVIEW

**Comment by sculpt0r** [comment]
Rebased on the newest master.

File: plugins/imagebase/plugin.js [hunk 1]
```diff
@@ -251,15 +251,15 @@
...
+					var dataTransfer = evt.data.dataTransfer,
+						isFileTransfer = dataTransfer && dataTransfer.isFileTransfer(),
 						filesCount = dataTransfer && dataTransfer.getFilesCount();
 
 					if ( editor.readOnly ) {
 						return;
 					}
 
-					if ( method === 'drop' || ( method === 'paste' && filesCount ) ) {
+					if ( isFileTransfer ) {
```
Comment (sculpt0r) [inline plugins/imagebase/plugin.js:262]: Maybe we could switch to an early return since this `if` is modified?

File: tests/plugins/easyimage/manual/wordintegration.md [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+1. Copy any text content from Word.
+1. Paste it into the editor
+
+## Expected
+
+Content is pasted as a text.
+
+## Unexpected
+
+Content is pasted as an image.
```
Comment (sculpt0r) [inline tests/plugins/easyimage/manual/wordintegration.md:16]: Expected and Unexpected could be inlined.

File: tests/plugins/easyimage/uploadintegrations.js [hunk 3]
```diff
@@ -1,7 +1,7 @@
 /* bender-tags: editor, clipboard, upload */
 /* bender-ckeditor-plugins: sourcearea, wysiwygarea, easyimage */
 /* bender-include: %BASE_PATH%/plugins/clipboard/_helpers/pasting.js, %BASE_PATH%/plugins/imagebase/features/_helpers/tools.js */
-/* global imageBaseFeaturesTools, pasteFiles, assertPasteEvent */
+/* global imageBaseFeaturesTools, assertPasteEvent */
```
Comment (sculpt0r) [inline tests/plugins/easyimage/uploadintegrations.js:4]: There are some problems with tests on IE8:
image

I think it is related to ignoring tests on unsupported environment:
```js
isSupportedEnvironment: function() {
			return !CKEDITOR.env.ie || CKEDITOR.env.version >= 11;
		},
```

Could you look at them?

**Review by sculpt0r — CHANGES_REQUESTED** [review]
@Comandeer - could you take a look mostly at tests at IE? There is an error so they don't finish in a clean way.

Also, I left a few more inline comments.

File: tests/plugins/easyimage/uploadintegrations.js (hunk 3 above)
Comment (Comandeer) [reply tests/plugins/easyimage/uploadintegrations.js:4]: It seems that `bender.ignore()` does not stop executing the rest of `init()` function. I've replaced it with simple early return and added additional `assert.ignore()` inside `setUp()` function.

**Comment by Comandeer** [comment]
I've refactored code a little by switching to suggested early return and fixed tests in IE.

File: tests/plugins/easyimage/uploadintegrations.js [hunk 4]
```diff
@@ -126,6 +127,11 @@
 			},
 
 			setUp: function() {
+				// We need to ignore entire test suit to prevent of fireing init, which breaks test suit on IE8-IE10.
+				if ( !this.editor.plugins.easyimage.isSupportedEnvironment() ) {
```
Comment (sculpt0r) [inline tests/plugins/easyimage/uploadintegrations.js:131]: Not sure if we should join this `if` with the below one?  To me, it is cleaner when they are separated. WDYT?

**Review by sculpt0r — CHANGES_REQUESTED** [review]
Thank you @Comandeer for the corrections. Previously broken tests are working fine now in IE.

I left one significant comment about ignoring manual tests on IE. Not sure if you left it intentionally since it shows that paste from Word doesn't create a widget with the uninitialized plugin?

Also a few comments about styling.

File: tests/plugins/easyimage/uploadintegrations.js (hunk 4 above)
Comment (Comandeer) [reply tests/plugins/easyimage/uploadintegrations.js:131]: I also think the same – that's why I left them separated.

**Comment by Comandeer** [comment]
I've rebased the PR onto the latest `master` and fixed all mentioned issues.

**Comment by sculpt0r** [comment]
Rebased on the newest master.

**Review by sculpt0r — APPROVED** [review]
LGTM 🎉 

Thank you @Comandeer for the refactoring and corrects. I've added a changelog entry.
