### PR TITLE
Fix strict mode: Move function declaration outside the switch statement

### LINKED ISSUE #5177: Editor crashes due to strict mode
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open local CKE4 sample.

### Expected result

The editor renders correctly.

### Actual result

The editor does not show up and there is an error in the console:

```
SCRIPT1047: In strict mode, function declarations cannot be nested inside a statement or block. They may only appear at the top level or directly inside a function body. 
range.js, line 1474 character 6
```

## Other details

* Browser: IE10
* OS: Windows 7
* CKEditor version: `master` (4.19.0)
* Installed CKEditor plugins: N/A

The issue is probably caused by 1cebbe557df3ceb0d47cf4e14077548b72bb8281.

### PR DESCRIPTION
**Pull request by sculpt0r**
…cope

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* none
```

## What changes did you make?

*Give an overview…*

## Which issues does your PR resolve?

Closes #5177 .

### CODE REVIEW

File: core/dom/range.js [hunk 1]
```diff
@@ -1261,6 +1261,54 @@ CKEDITOR.dom.range = function( root ) {
...
+
+				while ( ( node = walker.next() ) ) {
+					if ( node.type != CKEDITOR.NODE_TEXT ) {
+						// Stop if you enter to any node (walker.next() will return node only
+						// it goes out, not if it is go into node).
+						return false;
+					} else {
+						// Trim the first node to startOffset.
+						if ( node != startContainer )
+							siblingText = node.getText();
```
Comment (Comandeer) [inline core/dom/range.js:1299]: The `siblingText` variable is overridden here but it's also used outside of the function. Isn't there a case when not overriding the variable outside of this function would generate an incorrect result (like in line 1577)?

**Review by Comandeer — CHANGES_REQUESTED** [review]
Looks good, I only have one doubt (see my inline comments).

File: core/dom/range.js (hunk 1 above)
Comment (sculpt0r) [reply core/dom/range.js:1299]: TBH - I just put my trust in all tests we have so far... Also, those are the most complicated ones. It is even hard to name them correctly - since there are so many `if` cases to handling the `enlarging` the range 🤔 Eventually we should decide to create a separate PR for writing separate tests and refactor range functions. IMHO - since those logics are very old - we could say that they work stable. I'm not fully convinced whether we should make additional changes here without any explicit issue?

**Comment by sculpt0r** [comment]
@Comandeer - ready for another review.
- Moved the function according to the docs

File: core/dom/range.js (hunk 1 above)
Comment (Comandeer) [reply core/dom/range.js]: I'm not able to come up with a case that would break it 🤔 And you're right, our test case for ranges is pretty extensive and should catch it anyway.

**Review by Comandeer — CHANGES_REQUESTED** [review]
Although I couldn't break the new `onlyWhiteSpaces()` function, let's make the `siblingText` a variable scoped to the `CKEDITOR.dom.range#enlarge()` method just in case.

**Comment by sculpt0r** [comment]
@Comandeer - corrections are ready:
- I've moved the `siblingText` declaration to the top of `enlarge` definition and it is removed from arguments in `onlyWhiteSpaces`

Also, I've move the `boundary` definition to the top of `enlarge`. Previously it was declared in the second `case` and reassigned in the `third`. It is unused in the first `case`. So overall it will be good to see the declaration before the switch statement. But it is still passed to the `onlyWhiteSpaces` function.

**Review by Comandeer — APPROVED** [review]
LGTM! I've just removed one leftover `siblingText` argument and rebased onto latest `master`.
