### PR TITLE
Fix for incorrect replacing with phrases with several spaces inside

### LINKED ISSUE #5061: Multiple spaces in `find&replace` as 'replaced with' turns to a single space
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor4 sample: https://codepen.io/karoldawidziuk/pen/LYzJvdx
2. Click Find&Replace
3.  Provide text to be replaced, e.g. `h`
4. Provide text for replacement: use more than one space(e.g. 4 spaces)
5. Use Replace or Replace All button

### Expected result

*What is the expected result of the above steps?*
The letter `h` should be replaced with four spaces. Spaces probably will be encoded as `&nbsp;` mixed with casual spaces.

### Actual result

*What is the actual result of the above steps?*
Only a single space is used as a replacement.

## Other details
I can track the same behavior back to the `4.14.0` so i looks like no regression here

* Browser: all (Safari, FF, Chrome)
* OS: …
* CKEditor version: 4.17.1
* Installed CKEditor plugins: full-all

### PR DESCRIPTION
**Pull request by Comandeer**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#5061](https://github.com/ckeditor/ckeditor4/issues/5061): Fixed: [Find / Replace](https://ckeditor.com/cke4/addon/find) plugin incorrectly handles multiple whitespace during replacing text.
```

## What changes did you make?

Creating a text node from any text removes any consecutive whitespace. To prevent that I've added a `replace()` that replaced every odd space with a non-breaking one.

The only concern I have is if we want to replace all spaces with the non-breaking one or only "normal" spaces (` `)? For now the code replaces all of them.

## Which issues does your PR resolve?

Closes #5061.

### CODE REVIEW

**Comment by Comandeer** [comment]
It seems that this PR should be merged after #5066 as the other one is fixing failing `find` tests.

**Comment by Comandeer** [comment]
Rebased onto latest `master`.

File: plugins/find/dialogs/find.js [hunk 1]
```diff
@@ -486,8 +488,17 @@
...
-					var text = editor.document.createText( newString );
+					var domRange = this.matchRange.toDomRange(),
+						textWithPreservedSpaces = newString.replace( consecutiveWhitespaceRegex,
+							function( whitespace ) {
+								var newSpaces = CKEDITOR.tools.array.map( whitespace, function( space, i ) {
+									return i % 2 === 0 ? nonBreakingSpace : space;
+								} );
+
+								return newSpaces.join( '' );
+							} ),
```
Comment (KarolDawidziuk) [inline plugins/find/dialogs/find.js:499]: Overall code works good but let's move the replace logic into a separate function. It will look clearer.

File: tests/plugins/find/find.js [hunk 2]
```diff
@@ -263,6 +263,41 @@ bender.test( {
...
+	// (#5061)
+	'test replace all occurences of phrase with phrase with several spaces inside': function() {
+		var bot = this.editorBot;
+
+		bot.setHtmlWithSelection( '<p>[replace me]</p><p>replace me</p>' );
+
+		bot.dialog( 'replace', function( dialog ) {
+			dialog.setValueOf( 'replace', 'txtReplace', 'foo   bar' );
+			dialog.getContentElement( 'replace', 'btnReplaceAll' ).click();
+			dialog.getButton( 'cancel' ).click();
```
Comment (KarolDawidziuk) [inline tests/plugins/find/find.js:293]: We can remove this line because we hide dialog after assertion. ( line 297 )

**Review by KarolDawidziuk — CHANGES_REQUESTED** [review]
Hi, @Comandeer 
Overall everything is good and your fix works well.

There are some small style adjustments to add. Please see my inline comments.

File: tests/plugins/find/find.js [hunk 3]
```diff
@@ -263,6 +263,41 @@ bender.test( {
...
+
+			assert.areSame( '<p>foo&nbsp; &nbsp;bar</p><p>foo&nbsp; &nbsp;bar</p>', bot.getData( false, true ) );
```
[the remark this answers is not in the document]
Comment (Comandeer) [reply tests/plugins/find/find.js:295]: I've just copied the code from some previous tests :see\_no\_evil: I'll remove unnecessary parameters.

File: tests/plugins/find/manual/replacedoublespace.html [hunk 4]
```diff
@@ -0,0 +1,9 @@
+<textarea id="editor">
+	<p>Replace me</p>
+</textarea>
+
+<script>
+	CKEDITOR.replace( 'editor', {
+		language: 'en'
```
[the remark this answers is not in the document]
Comment (Comandeer) [reply tests/plugins/find/manual/replacedoublespace.html:7]: No, it's not. Leftover from testing in my Chrome that makes the editor using Polish :upside\_down\_face:

File: tests/plugins/find/find.js (hunk 2 above)
Comment (Comandeer) [reply tests/plugins/find/find.js:293]: Actually, I've moved it before the assertion in both tests. Otherwise, if the assertion failed, the dialog wouldn't be closed.

**Comment by Comandeer** [comment]
I've moved the logic into a separate function and updated tests – switching also from "Replace" to "Replace All" (as "Replace" need two clicks and "Replace All" only one) in them. Also rebased the PR onto latest `master`.

**Review by KarolDawidziuk — APPROVED** [review]
Thanks, @Comandeer for the improvements.
For me, everything looks good, so it's R+ from my side. 🎉

File: plugins/find/dialogs/find.js [hunk 5]
```diff
@@ -826,6 +829,19 @@
 				}
 			}
 		};
+
+		function createTextNodeWithPreservedSpaces( editor, text ) {
+			var textWithPreservedSpaces = text.replace( consecutiveWhitespaceRegex,
+				function( whitespace ) {
+					var newSpaces = CKEDITOR.tools.array.map( whitespace, function( space, i ) {
```
Comment (jacekbogdanski) [inline plugins/find/dialogs/find.js:836]: `CKEDITOR.tools.array.map` function takes an array as an argument, not a string. This code takes advantage of strings defining iterator, but it reduces code readability.

**Review by jacekbogdanski — CHANGES_REQUESTED** [review]
We are missing a case when text includes additional space at the end of a phrase, e.g. `foobar<space>`. I've added a test in https://github.com/ckeditor/ckeditor4/pull/5065/commits/76d3d0131a3dc31fbb3b72221367a91bb6c32e07 confirming that issue.

**Comment by Comandeer** [comment]
> We are missing a case when text includes additional space at the end of a phrase

Spaces at the end of phrases are preserved as long as the end of the phrase is not the same as the end of the paragraph. In such a case it seems to be a totally separate issue, connected with how `CKEDITOR.dom.range#insertNode()` works (see #5074). In that case, I propose to simply remove the failing test and resolve that issue separately.

**Comment by jacekbogdanski** [comment]
Alright, thanks for checking this out and extracting a follow-up ticket. Let's wait for CI and if it's green we can merge this PR 🎉

**Review by jacekbogdanski — APPROVED** [review]
