### PR TITLE
Fix: Html comments in widgets not processed correctly

### LINKED ISSUE #4777: Html comments in widgets not processed correctly
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor4/latest/examples/simplebox.html, click the 'source' button, and paste in the HTML from the attached text file.
[20210625-ckeditor-4777.txt](https://github.com/ckeditor/ckeditor4/files/6714836/20210625-ckeditor-4777.txt)

2. Toggle the 'source' button on and off several times.

### Expected result

The text remains unchanged.

### Actual result

Each cycle of toggling the 'source' button adds the text '{C}' to the front and end of the text. (The '{C}' is actually added before the <!-- of each comment.) 

## Other details

I'm experiencing this problem with a widget on our Drupal-based website that uses HTML comments within its markup. But when I debugged the widget's javascript it seems the '{C}' is added by ckeditor's code, not the widget. I confirmed that by using the simplebox example, which shows the same problem.

The problem started when I changed our copy of CKEditor from //cdn.ckeditor.com/4.14.0/full-all to //cdn.ckeditor.com/4.16.1/full-all after a recent security advisory. Changing it back to 4.14.0 stops the problem again.

Though the 'code' button can be used to show the problem, it also happens every time the user opens a page to edit it. So on our site, pages that are edited several times have long strings of '{C}{C}...{C}{C}' added.

## Other details

* Browser: Google Chrome Version 91.0.4472.114 (Official Build) (64-bit)
* OS: Win10
* CKEditor version: 4.16.1
* Installed CKEditor plugins: whatever is used at https://ckeditor.com/docs/ckeditor4/latest/examples/simplebox.html

### PR DESCRIPTION
**Pull request by sculpt0r**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [X] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [X] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4777](https://github.com/ckeditor/ckeditor4/issues/4777): Fixed: Html comments in widgets not processed correctly
```

## What changes did you make?

The origin of this regression here is merge: https://github.com/ckeditor/ckeditor4/pull/4618

In older version: `unprotectSource` was also invoked, but data there was already cleared after comments protection. To restore previous data flow without breaks on last fix I simply unprotect html comments before the source is unprotected. This requires to make one more method from `htmldataprocessor` to be public: `unprotectRealComments`.

## Which issues does your PR resolve?

Closes #4777 .

### CODE REVIEW

File: plugins/widget/plugin.js [hunk 1]
```diff
@@ -1928,6 +1928,9 @@
 			}
 			this._.initialSetData = false;
 
+			// Unprotect comments, to get rid of additionall characters (#4777).
+			data = this.editor.dataProcessor.unprotectRealComments( data );
```
Comment (jacekbogdanski) [inline plugins/widget/plugin.js:1932]: additionall
```suggestion
			// Unprotect comments, to get rid of additional characters (#4777).
			data = this.editor.dataProcessor.unprotectRealComments( data );
```

**Review by jacekbogdanski — APPROVED** [review]
