### PR TITLE
Fix CORS issue for Emoji SVG icons

### LINKED ISSUE #2607: Emoji plugin - iconsall.svg not loaded in CORS context
## Type of report

Bug

## Provide detailed reproduction steps (if any)

When getting CKEDITOR from a domain different than the website the user is navigating on, the emoji plugin doesn't succeed to load iconsall.svg file because of domains error. Here is the detailed error sent by Chrome:

`Unsafe attempt to load URL https://static.mywebsite.com/ckEditor/plugins/emoji/assets/iconsall.svg?t=IA8F from frame with URL https://www.mywebsite.com/my-page/. Domains, protocols and ports must match.`

Note that a GET request to the URL `https://static.mywebsite.com/ckEditor/plugins/emoji/assets/iconsall.svg?t=IA8F` got the appropriate headers:

```
access-control-allow-headers: *
access-control-allow-methods: GET, OPTIONS
access-control-allow-origin: *
```

### Expected result

iconsall.svg should load and Emoji Navigation Items should display.

### Actual result

iconsall.svg is not loading neither Emoji Navigation Items.

## Other details

* Browser: Chrome / Firefox (not tested others)
* OS: Windows (not tested others)
* CKEditor version: 4.11.1
* Installed CKEditor plugins: Emoji

### PR DESCRIPTION
**Pull request by jacekbogdanski**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#2607](https://github.com/ckeditor/ckeditor4/issues/2607): Fixed: Emoji SVG icons are not loaded due to CORS .
```

## What changes did you make?

Instead of external SVG links, XML is moved inside emoji panel to get around CORS issue.

**Note** that manual test uses https://githack.com development CDN to emulate different domain context. It should be replaced with our CDN for `4.14.1` once released. Tell if you are fine with a manual tests, so I can extract a followup ticket for it.

## Which issues does your PR resolve?

Closes #2607

### CODE REVIEW

File: tests/plugins/emoji/dropdown.js [hunk 1]
```diff
@@ -359,6 +359,35 @@
...
+
+					container.setHtml( html );
+
+					resume( function() {
+						var icons = doc.findOne( '.cke_emoji-navigation_icons' );
+
+						assert.beautified.html( container.getHtml(), icons.getHtml(), 'Icons should be loaded as a part of panel' );
+
+						panel.hide();
+					} );
```
Comment (f1ames) [inline tests/plugins/emoji/dropdown.js]: This code mocks most of the logic from `loadSVGNavigationIcons()` method which means it doesn't really test it. Wouldn't it be possible to call `loadSVGNavigationIcons()` here or create more integration like test so the ajax call would be performed by the plugin itself?

File: plugins/emoji/plugin.js [hunk 2]
```diff
@@ -342,14 +343,13 @@
 						'</div>';
 				},
 				getLoupeIcon: function() {
-					var loupeSvgUrl = CKEDITOR.getUrl( this.plugin.path + 'assets/iconsall.svg' ),
-						loupePngUrl = CKEDITOR.getUrl( this.plugin.path + 'assets/iconsall.png' ),
+					var loupePngUrl = CKEDITOR.getUrl( this.plugin.path + 'assets/iconsall.png' ),
 						useAttr;
 
 					if ( CKEDITOR.env.ie && !CKEDITOR.env.edge ) {
```
[the remark this answers is not in the document]
Comment (jacekbogdanski) [reply plugins/emoji/plugin.js]: No reason, simple oversight.

File: tests/plugins/emoji/dropdown.js (hunk 1 above)
Comment (jacekbogdanski) [reply tests/plugins/emoji/dropdown.js]: What do you mean about mocking? :thinking: Ajax request in unit test loads SVG HTML for the simpler assertion, so we don't need to copy the same HTML in 2 different places. But `loadSVGNavigationIcons` is called without any mocking by the panel itself once opened.

Comment (f1ames) [reply tests/plugins/emoji/dropdown.js]: > Ajax request in unit test loads SVG HTML for the simpler assertion, so we don't need to copy the same HTML in 2 different places. But `loadSVGNavigationIcons` is called without any mocking by the panel itself once opened.

Ok, I see now, I somehow missed that, thinking that icons loading is done only by ajax request  :thinking: So this test does exactly what I thought it should :+1:

**Comment by f1ames** [comment]
I have rechecked failing Safari unit test and it still fails on \`master\`, meaning it's not related to this PR.
