### PR TITLE
Fix customConfig race condition

### LINKED ISSUE #3361: customConfig conflicts with other CKEDitor instance customConfig
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I'm using [Pimcore](https://pimcore.com/de) as Content Management System, which implements CKEditor as their WYSIWYG editor for rich text fields. It allows specifying a `customConfig` file ([Reference](https://pimcore.com/docs/5.x/Development_Documentation/Documents/Editables/WYSIWYG.html#page_Configuration)) for each field, which will be passed to CKEditor. This is a follow-up from https://github.com/pimcore/pimcore/issues/1124 since Pimcore mentioned that the following bug is related to CKEditor itself.

In the backend interface, where users can edit fields using CKEditor, I have several different fields on one page, all with an individual CKEditor instance and sometimes with different configuration files (`customConfig`).

Imagine the following situation:

One instance of CKEditor for field A with the following custom config file contents (acutally doesn't matter, it's just differently to the other field below):

```javascript
CKEDITOR.editorConfig = function(config) {
  config.enterMode = CKEDITOR.ENTER_BR;
  config.shiftEnterMode = CKEDITOR.ENTER_BR;
  config.autoParagraph = false;
  config.removeButtons = 'Form,Checkbox,Radio,TextField,Textarea,Select,Button,HiddenField,Anchor,Image,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe,Format,Font,FontSize,Styles,About,NumberedList,BulletedList,Outdent,Indent,CreateDiv,JustifyLeft,JustifyRight,JustifyBlock,BidiLtr,BidiRtl,JustifyCenter,Language,Link,Unlink,Anchor,Image,Flash,Table,HorizontalRule,Smiley,Iframe,PageBreak,Blockquote';
  config.disallowedContent = 'a';
};
```

Then another instance of CKEditor for field B with the following custom config file contents (acutally doesn't matter, it's just differently to the other field above):

```javascript
CKEDITOR.editorConfig = function(config) {
  config.removeButtons = 'Image';
  config.disallowedContent = 'img';
};
```

And finally, another CKEditor instance for field C with the exact same custom config file like field A.

Now, in this case field C should have the exact same toolbar like field A, because they are referencing to the same `customConfig` file. But because field B - with a separate CKEditor instance - is rendered between those two fields, with a different configuration, field C and any subsequent CKEditor instance gets the configuration of field B - __the wrong__ configuration.

So, just to visualize the issue, this is the toolbar for field A:

In this screenshot you can also see field B ("Content"), which has a different `customConfig`.

And this is the config for field C:

In this screenshot you can see that field C get's a the wrong toolbar, it should look like field A.

### Expected result

A CKEditor instance should always use the provided `customConfig`.

### Actual result

When mixing several CKEditor instances with different `customConfig` files, CKEditor uses the wrong configuration.

## Other details

* Browser: Firefox (latest, 70)
* OS: Windows 10
* CKEditor version: 4.11.2
* Installed CKEditor plugins: None

### PR DESCRIPTION
**Pull request by jacekbogdanski**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#3361](https://github.com/ckeditor/ckeditor4/issues/3361): Fixed: Loading multiple [custom editor configurations](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-customConfig) is prone to race condition between them.
```

## What changes did you make?

Honestly, I was really wondering about rewriting the whole `customConfig` loading as it could be nicely simplified and the current implementation is pretty bloated. Although, it's not a very good idea to do with a core code 10 years old. I propose simple fix instead, making sure that we won't overwrite cached config functor by a closure race condition. 

## Which issues does your PR resolve?

Closes #3361.

### CODE REVIEW

File: tests/core/editor/custom_config_race.js [hunk 1]
```diff
@@ -1,41 +1,66 @@
...
-						plugins: 'wysiwygarea',
-						on: {
-							instanceReady: function() {
-								if ( ++count == total )
-									callback();
+var assetsPath = '%TEST_DIR%_assets/';
+
+function initEditors( editors ) {
+	var count = 0;
+	var instances = {};
```
Comment (Dumluregn) [inline tests/core/editor/custom_config_race.js:7]: No need for duplicated `var` keyword I guess?

File: tests/core/editor/custom_config_race.js [hunk 2]
```diff
@@ -1,41 +1,66 @@
...
+	return function( callback ) {
+		var total = CKEDITOR.tools.object.keys( editors ).length;
+
+		for ( var e in editors ) {
+			instances[ e ] = CKEDITOR.replace( e,
+				CKEDITOR.tools.extend( editors[ e ], {
+					plugins: 'wysiwygarea',
+					on: {
+						instanceReady: function() {
+							if ( ++count == total ) {
```
Comment (Dumluregn) [inline tests/core/editor/custom_config_race.js:18]: ~Someone once told me that using increment operator is good only in `for` loop declaration as it decreases the readability everywhere else, WDYT? 😄~ Now I see you just outdented this part of code so my joke was inappropriate 🤷‍♂️ Still, maybe let's switch it to a simple
```js
count++;

if ( count == total ) {
```
for the sake of future CKE4 maintainers.

File: tests/core/editor/custom_config_race.js [hunk 3]
```diff
@@ -1,41 +1,66 @@
...
 			editor1: { customConfig: assetsPath + 'raceconfig1.js' },
 			editor2: { customConfig: assetsPath + 'raceconfig2.js' },
-			editor3: { customConfig: assetsPath + 'raceconfig3.js' }
-		}, this.callback );
+			editor3: { customConfig: assetsPath + 'raceconfig1.js' }
+		} )
+		( function( instances ) {
+			assert.areSame( '200px', instances.editor1.config.width, 'Instance uses own customConfig.' );
+			assert.areSame( '300px', instances.editor2.config.width, 'Instance uses own customConfig.' );
+			assert.areSame( '200px', instances.editor3.config.width, 'Instance uses own customConfig.' );
```
Comment (Dumluregn) [inline tests/core/editor/custom_config_race.js:50]: AFAIK the last parameter here is an error message, so something like `Instance should use own customConfig.` or `Instance didn't use own customConfig.` could be a little more precise communicate.

File: tests/core/editor/custom_config_race.js [hunk 4]
```diff
@@ -1,41 +1,66 @@
...
-		assert.areSame( '400px', instances.editor3.config.width, 'Instance uses own customConfig.' );
+		initEditors( {
+			editor1: { customConfig: assetsPath + 'raceconfig1.js' },
+			editor2: { customConfig: assetsPath + 'raceconfig2.js' },
+			editor3: { customConfig: assetsPath + 'raceconfig3.js' }
+		} )
+		( function( instances ) {
+			assert.areSame( '200px', instances.editor1.config.width, 'Instance uses own customConfig.' );
+			assert.areSame( '300px', instances.editor2.config.width, 'Instance uses own customConfig.' );
+			assert.areSame( '400px', instances.editor3.config.width, 'Instance uses own customConfig.' );
```
Comment (Dumluregn) [inline tests/core/editor/custom_config_race.js:63]: The comment about error message applies here too.

File: tests/core/editor/manual/customconfigrace.html [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+<div id="editor1"></div>
+<h2>Editor 2</h2>
+<div id="editor2"></div>
+<h2>Editor 3</h2>
+<div id="editor3"></div>
+
+<script>
+	var assetsPath = '%BASE_PATH%core/editor/_assets/',
+		config1 = assetsPath + 'raceconfig1.js',
+		config2 = assetsPath + 'raceconfig3.js';
```
Comment (Dumluregn) [inline tests/core/editor/manual/customconfigrace.html:11]: I guess you chose `raceconfig3.js` instead of `raceconfig2.js` here to make the difference in editors width as clear as possible, but at first glance it looks like a typo. I checked how does it look with `raceconfig2.js` and I think it will still be easy to verify 👍

File: tests/core/editor/manual/customconfigrace.md [hunk 6]
```diff
@@ -0,0 +1,14 @@
+@bender-tags: bug, 4.14.2, 3361
+@bender-ui: collapsed
+@bender-ckeditor-plugins: toolbar, wysiwygarea, basicstyles
+
+Verify editors width.
+
+## Expected
+
+* Editor 1 and Editor 3 have the same width (`200px`).
+* Editor 2 have different width (`400px`).
```
Comment (Dumluregn) [inline tests/core/editor/manual/customconfigrace.md:10]: If you agree with me on the change of `configfile` used in the test, this should be changed to `300px`.

File: tests/core/editor/manual/customconfigrace.md [hunk 7]
```diff
@@ -0,0 +1,14 @@
...
+
+## Unexpected
+
+Editor 2 and Editor 3 have the same width. (`400px`).
```
Comment (Dumluregn) [inline tests/core/editor/manual/customconfigrace.md:14]: And also here - `400px` -> `300px`.

File: core/editor.js [hunk 8]
```diff
@@ -275,19 +276,19 @@
 
 			// If there is no other customConfig in the chain, fire the
 			// "configLoaded" event.
-			if ( CKEDITOR.getUrl( editor.config.customConfig ) == customConfig || !loadConfig( editor ) )
+			if ( CKEDITOR.getUrl( editor.config.customConfig ) == customConfig || !loadConfig( editor ) ) {
 				editor.fireOnce( 'customConfigLoaded' );
+			}
+
```
Comment (Dumluregn) [inline core/editor.js:282]: I think we don't usually leave an empty line before the closing brackets, so there is no need for adding one here.

File: tests/core/editor/custom_config_race.js (hunk 2 above)
Comment (jacekbogdanski) [reply tests/core/editor/custom_config_race.js:18]: It's really nice to see how sides turned out! Indeed I didn't pay enough attention to leave this code better then I found it.

File: core/editor.js (hunk 8 above)
Comment (jacekbogdanski) [reply core/editor.js:282]: I've added this line because at the first glance outer `else` looks like it belongs to this inner `if`.
image
**vs**
image

Comment (Dumluregn) [reply core/editor.js:282]: Ok, we can leave it this way :+1:
