### PR TITLE
Fix issue with loosing keybindings for autocomplete panel with sourcemode

### LINKED ISSUE #3938: Autocomplete loses navigation keybindings after switching source mode
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open any sample with autocomplete and sourcearea plugins.
2. Switch between source editing and content editing.
3. Trigger autocompletion.
4. Navigate using arrow keys.

### Expected result

You can navigate through the completion panel using a keyboard.

### Actual result

Keybindings are removed.

## Other details

Probably standard issue with incorrect event listener on editable where we should use `attachListener` instead:
https://github.com/ckeditor/ckeditor4/blob/5ace43e789f84c74f74fb1b163715aa2ba04e826/plugins/autocomplete/plugin.js#L307-L309

### PR DESCRIPTION
**Pull request by jacekbogdanski**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
*[#3938](https://github.com/ckeditor/ckeditor4/issues/3938): Fixed: Autocomplete loses navigation keybindings after switching source mode.
```

## What changes did you make?

Corrected attaching events to editable.

## Which issues does your PR resolve?

Closes #3938

### CODE REVIEW

File: tests/plugins/autocomplete/autocomplete.js [hunk 1]
```diff
@@ -157,6 +162,32 @@
 			wait();
 		},
 
+		// (#3938)
+		'test navigation keybindings are registered after changing mode': function() {
```
Comment (f1ames) [inline tests/plugins/autocomplete/autocomplete.js]: This test fails on IE9:

image

Since manual test passes it seems the fix is working correctly there. If this test is not super easy to fix there, we may just ignore it.

File: plugins/autocomplete/plugin.js [hunk 2]
```diff
@@ -288,26 +288,28 @@
...
+			editor.on( 'contentDom', this.registerPanelNavigation, this );
+		},
+
+		registerPanelNavigation: function() {
+			var editable = this.editor.editable();
+
+			// Priority 5 to get before the enterkey.
+			// Note: CKEditor's event system has a limitation that one function (in this case this.onKeyDown)
+			// cannot be used as listener for the same event more than once. Hence, wrapper function.
+			this._listeners.push( editable.attachListener( editable, 'keydown', function( evt ) {
```
[the remark this answers is not in the document]
Comment (jacekbogdanski) [reply plugins/autocomplete/plugin.js]: Yes, keeping old editable instance in a closure was the main issue here, but as you wrote, `attachListener` suits better here.

File: tests/plugins/autocomplete/autocomplete.js (hunk 1 above)
Comment (jacekbogdanski) [reply tests/plugins/autocomplete/autocomplete.js]: It looks like IE9 has some weird problem with removing editable listeners once editable has been detached. I was able to reproduce the issue only using bender (it works fine using samples). It seems like dropping destroying autocomplete removes this issue. Destroying autocomplete is not really important in this test as it uses its own editor instance, so it's probably better than ignoring this test on IE9, WDYT?

Comment (f1ames) [reply tests/plugins/autocomplete/autocomplete.js:166]: > Destroying autocomplete is not really important in this test as it uses its own editor instance, so it's probably better than ignoring this test on IE9, WDYT?

Makes sense for me. It's always better to have a working test :+1:

**Comment by f1ames** [comment]
Rebased onto latest `master`.
