### PR TITLE
Fix scrollIntoView method (replace type to getType())

### LINKED ISSUE #4041: The scrollIntoView() method uses non-existent "selection.type" property
https://github.com/ckeditor/ckeditor4/blob/8a12b041718e05eeffb62a931d95995ac72cbe22/core/selection.js#L2495

`this.type` in the code above is always "undefined" as the `type` is not being maintained anywhere else. The correct reference call should be `this.getType()`.

### PR DESCRIPTION
**Pull request by hub33k**
## What is the purpose of this pull request?

Bug fix.

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
*[#4041](https://github.com/ckeditor/ckeditor4/issues/4041): Fix scrollIntoView method (replace type with getType()).
```

## What changes did you make?

Removes non-existing `type` property and replace it with `getType()` method.

## Which issues does your PR resolve?

Closes #4041.

### CODE REVIEW

File: core/selection.js [hunk 1]
```diff
@@ -2495,7 +2495,7 @@
 		 */
 		scrollIntoView: function() {
 			// Scrolls the first range into view.
-			if ( this.type != CKEDITOR.SELECTION_NONE )
+			if ( this.getType() != CKEDITOR.SELECTION_NONE )
 				this.getRanges()[ 0 ].scrollIntoView();
```
Comment (jacekbogdanski) [inline core/selection.js:2499]: Please, [always use brackets for a single line statement](https://github.com/ckeditor/ckeditor4/blob/master/dev/docs/codestyle.md#2212-always-use-brackets-even-for-a-single-line-statements).

File: tests/core/selection/manual/scrollintoview.html [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+				exec: function ( editor ) {
+					editor.getSelection().scrollIntoView();
+				},
+			} );
+
+			editor.ui.addButton( 'Test', {
+				label: 'Scroll to selection',
+				command: 'test',
+				directional: true,
+				icon: 'https://ckeditor.com/docs/assets/1.2.4/img/cog.svg'
```
Comment (jacekbogdanski) [inline tests/core/selection/manual/scrollintoview.html:53]: It's nice that you used real icon - I hate these manual tests where you have to search for an invisible button :smile: However, it may be safer to copy this icon into local test assets and use it instead, so we make sure it never disappears. You can check how it has been done for `lena.png` file using `%BASE_PATH%` magic keyword - https://github.com/ckeditor/ckeditor4/blob/91306a9342bb663ff499bb2841183bfda89c18b7/tests/plugins/balloontoolbar/manual/focus.html#L6-L34 which resolves into bender browser URL.

File: tests/core/selection/manual/scrollintoview.md [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+@bender-ui: collapsed
+@bender-ckeditor-plugins: wysiwygarea, divarea, toolbar
+
+1. Place cursor at the end of `Welcome letter`.
+1. Scroll to the end of editor.
+1. Press cog button.
+
+## Expected
+
+You should be scrolled to `Welcome letter` string.
```
Comment (jacekbogdanski) [inline tests/core/selection/manual/scrollintoview.md:11]:
```suggestion
You should be scrolled to `Welcome letter` text line.
```

File: tests/core/selection/manual/scrollintoview.md [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+
+## Unexpected
+
+You are not scrolled to `Welcome letter` string.
```
Comment (jacekbogdanski) [inline tests/core/selection/manual/scrollintoview.md:15]:
```suggestion
You are not scrolled to `Welcome letter` text line.
```

File: tests/core/selection/manual/scrollintoview.md [hunk 5]
```diff
@@ -0,0 +1,15 @@
+@bender-tags: selection, 4.14.1, bug, 4041
```
Comment (jacekbogdanski) [inline tests/core/selection/manual/scrollintoview.md:1]:
```suggestion
@bender-tags: selection, 4.14.2, bug, 4041
```

File: tests/core/selection/manual/scrollintoview.html [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+		<tr>
+			<td>1:00 PM - 3:00 PM</td>
+			<td>Pappardelle al pomodoro - live cooking session with <strong>Rita Fresco</strong></td>
+		</tr>
+		<tr>
+			<td>5:00 PM - 8:00 PM</td>
+			<td>Tuscan vineyards at a glance - wine-tasting session with <strong>Frederico Riscoli</strong></td>
+		</tr>
+		</tbody>
+	</table>
```
Comment (jacekbogdanski) [inline tests/core/selection/manual/scrollintoview.html:36]: There is some indentation issue within a table element - some elements are not correctly indented. Like rows are on the same level as `thead/tbody`.

File: tests/core/selection/manual/scrollintoview.html [hunk 7]
```diff
@@ -0,0 +1,69 @@
...
+
+	CKEDITOR.plugins.add( 'test', plugin );
+
+	CKEDITOR.replace( 'editor', {
+		height: 250,
+		extraPlugins: 'test',
+		toolbar: [ {
+				name: 'demo',
+				items: [ 'Test' ]
+			} ],
```
Comment (jacekbogdanski) [inline tests/core/selection/manual/scrollintoview.html:66]: A bit too much indented (by 1 tab).
