### PR TITLE
Disallow creating anchors with space characters

### LINKED ISSUE #5305: Anchor name can invalidly include spaces
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Start with CodePen https://codepen.io/karoldawidziuk/pen/LYzJvdx.
2. Select "Please find below the full schedule of the event."
3. Copy that string of text.
4. Click the Anchor icon.
5. In the Anchor Name field, paste the entire string of text.
6. Click OK.

### Expected result

Option 1. Get error message that the anchor name includes whitespace.
Option 2. Continue here and see option 2 expected result below.

### Actual result

Continue here without error message.

## Reproduction steps continued

7. Scroll to top of edit area
8. Select the words "The Flavorful Tuscany Meetup"
9. Click the link icon
10. Change Link type to Link to anchor in the text
11. Click the down arrow in the By Element ID dropdown

### Expected result

Option 2: See dropdown item "Please_find_below_the_full_schedule_of_the_event." or "Pleasefindbelowthefullscheduleoftheevent."

### Actual result

See dropdown item "Please find below the full schedule of the event."

## Other details

* Browser: Firefox 103.0.1
* OS: macOS 12.5
* CKEditor version: Whichever version is used by CodePen https://codepen.io/karoldawidziuk/pen/LYzJvdx on August 3, 2022.
* Installed CKEditor plugins: Whichever plugins are used by CodePen https://codepen.io/karoldawidziuk/pen/LYzJvdx on August 3, 2022.

* Standard cited for this issue: [HTML 5.2 Recommendation concerning the ID attribute](https://www.w3.org/TR/2021/SPSD-html52-20210128/dom.html#element-attrdef-global-id).

> When specified on [HTML elements](https://www.w3.org/TR/2021/SPSD-html52-20210128/infrastructure.html#html-element), the [id](https://www.w3.org/TR/2021/SPSD-html52-20210128/dom.html#element-attrdef-global-id) attribute value must be unique amongst all the [IDs](https://www.w3.org/TR/dom/#concept-id) in the element’s [tree](https://www.w3.org/TR/2021/SPSD-html52-20210128/infrastructure.html#tree) and must contain at least one character. The value must not contain any [space characters](https://www.w3.org/TR/2021/SPSD-html52-20210128/infrastructure.html#space-characters).

### PR DESCRIPTION
**Pull request by KarolDawidziuk**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#5305](https://github.com/ckeditor/ckeditor4/issues/5305): Fixed. Anchor name can invalidly include spaces.
```

## What changes did you make?

I've updated a `validate` method in anchor dialog by checking if the given name a **space** character.

## Which issues does your PR resolve?

Closes #5305.

### CODE REVIEW

File: tests/plugins/link/anchor.js [hunk 1]
```diff
@@ -207,6 +208,56 @@
 
 				assert.beautified.html( expected, editor.getData(), 'Prevent duplicated anchors failed in the ordered list with styled word' );
 			} );
+		},
+		// (#4802)
+		'test prevent adding anchor with SPACE character': function() {
+			assertWhitespaceAnchor( this.editorBot, '\u0020', 'SPACE' );
+		},
+
+			// (#4802)
```
Comment (Comandeer) [inline tests/plugins/link/anchor.js:217]:
```suggestion
		// (#4802)
```

File: tests/plugins/link/anchor.js [hunk 2]
```diff
@@ -207,6 +208,56 @@
...
+		'test prevent adding anchor with CHARACTER TABULATION character': function() {
+			assertWhitespaceAnchor( this.editorBot, '\u0009', 'CHARACTER TABULATION' );
+		},
+
+			// (#4802)
```
Comment (Comandeer) [inline tests/plugins/link/anchor.js:222]:
```suggestion
		// (#4802)
```

File: tests/plugins/link/anchor.js [hunk 3]
```diff
@@ -207,6 +208,56 @@
...
+		'test prevent adding anchor with FORM FEED character': function() {
+			assertWhitespaceAnchor( this.editorBot, '\u000c', 'FORM FEED' );
+		},
+
+			// (#4802)
```
Comment (Comandeer) [inline tests/plugins/link/anchor.js:227]:
```suggestion
		// (#4802)
```

File: tests/plugins/link/anchor.js [hunk 4]
```diff
@@ -207,6 +208,56 @@
 
 				assert.beautified.html( expected, editor.getData(), 'Prevent duplicated anchors failed in the ordered list with styled word' );
 			} );
+		},
+		// (#4802)
```
Comment (Comandeer) [inline tests/plugins/link/anchor.js:212]: Please update all issue references to the correct one (#5305).

File: plugins/link/dialogs/anchor.js [hunk 5]
```diff
@@ -136,10 +136,20 @@ CKEDITOR.dialog.add( 'anchor', function( editor ) {
 				label: editor.lang.link.anchor.name,
 				required: true,
 				validate: function() {
-					if ( !this.getValue() ) {
+					var disallowedWhitespacesRegex = /[\u0020\u0009\u000c]/g,
```
Comment (Comandeer) [inline plugins/link/dialogs/anchor.js:139]: I would add also new line and carriage return characters here – just to be sure. They aren't possible to but they can be pasted from somewhere. Better safe than sorry.

It'd be also nice to link to the spec to explain why these characters are not allowed.

File: plugins/link/lang/en.js [hunk 6]
```diff
@@ -13,6 +13,7 @@ CKEDITOR.plugins.setLang( 'link', 'en', {
 		title: 'Anchor Properties',
 		name: 'Anchor Name',
 		errorName: 'Please type the anchor name',
+		errorWhitespace: 'Anchor name cannot contain whitespaces',
```
Comment (Comandeer) [inline plugins/link/lang/en.js:16]:
```suggestion
		errorWhitespace: 'Anchor name cannot contain any whitespace',
```

Whitespace is mostly used as an uncountable noun.

File: tests/plugins/link/anchor.js [hunk 7]
```diff
@@ -207,6 +208,56 @@
...
+
+			bot.setHtmlWithSelection( template );
+			bot.dialog( 'anchor', function( dialog ) {
+				dialog.setValueOf( 'info', 'txtName', 'Foo\u00a0bar' );
+				dialog.getButton( 'ok' ).click();
+
+				assert.areEqual( 0, windowStub.callCount );
+			} );
+
+			windowStub.restore();
```
Comment (Comandeer) [inline tests/plugins/link/anchor.js:241]: Probably moving the restoration to the `tearDown()` function would be more convenient.

Otherwise, it would be good to put the restoration before any assertions. Currently, if assertions fail, the `alert()` stub won't be restored, leading to errors when stubbing the `alert()` in subsequent tests.

**Review by Comandeer — CHANGES_REQUESTED** [review]
Overall looks good! Just some minor things to polish.

**Comment by KarolDawidziuk** [comment]
Thanks, @Comandeer for the review - it's ready for another one.

File: tests/plugins/link/anchor.js (hunk 7 above)
Comment (KarolDawidziuk) [reply tests/plugins/link/anchor.js]: Moved restoration before assertion because IMO we don't need to tear down before any tests.

File: plugins/link/lang/en.js (hunk 6 above)
Comment (KarolDawidziuk) [reply plugins/link/lang/en.js]: I've changed it to a space character, not a whitespace.

File: plugins/link/dialogs/anchor.js (hunk 5 above)
Comment (KarolDawidziuk) [reply plugins/link/dialogs/anchor.js]: I've added a `new line` and `carriage return` character but I was not able to add a unit test to it as it was impossible to paste it to input. Are we okay with it? 🤔 

I've also added also short information about disallowed characters from spec.

File: tests/plugins/link/anchor.js [hunk 8]
```diff
@@ -1,10 +1,11 @@
 /* bender-tags: editor */
-/* bender-ckeditor-plugins: link,toolbar,basicstyles */
+/* bender-ckeditor-plugins: link,toolbar,basicstyles,notification */
```
[the remark this answers is not in the document]
Comment (KarolDawidziuk) [reply tests/plugins/link/anchor.js]: No, it's a leftover. Removed.

**Comment by Comandeer** [comment]
Rebased onto the latest `master`.

File: plugins/link/dialogs/anchor.js [hunk 9]
```diff
@@ -136,10 +136,23 @@ CKEDITOR.dialog.add( 'anchor', function( editor ) {
 				label: editor.lang.link.anchor.name,
 				required: true,
 				validate: function() {
-					if ( !this.getValue() ) {
+					// W3C HTML 5.2 Recommendation; §3.2.5:
```
Comment (Comandeer) [inline plugins/link/dialogs/anchor.js:139]: The HTML 5.2 specification does not longer exist. Could you update the reference to point to https://html.spec.whatwg.org/multipage/dom.html#global-attributes ?

File: plugins/link/lang/en.js [hunk 10]
```diff
@@ -13,6 +13,7 @@ CKEDITOR.plugins.setLang( 'link', 'en', {
 		title: 'Anchor Properties',
 		name: 'Anchor Name',
 		errorName: 'Please type the anchor name',
+		errorWhitespace: 'Anchor name cannot contain space character',
```
Comment (Comandeer) [inline plugins/link/lang/en.js:16]: There is some small discrepancy between this message and the message in the manual test. IMO the version from the test ("space character**s**") sounds better than the version in language files ("space character").

Probably it's safer to consult it with our docs team to ensure that the grammatical form of the message is ok 🤔 It would be much harder to do that _after_ the release.

**Review by Comandeer — CHANGES_REQUESTED** [review]
Looks good, only some polishing needed.

There is also an error in IE8 connected to the tests:

Error: Can't move focus to the control because it is invisible, not enabled, or of a type that does not accept the focus.

Could you look into it?

File: plugins/link/lang/en.js (hunk 10 above)
Comment (KarolDawidziuk) [reply plugins/link/lang/en.js:16]: After talking with @godai78 we have 3 possible options:

1. `Anchor name cannot contain space characters` -> your version
2. `Anchor name cannot contain any spaces` -> this may be not obvious
3. `Anchor name cannot contain any space characters`

For me, 1 and 3 look equally good to me, WDYT?

**Comment by KarolDawidziuk** [comment]
Thanks, @Comandeer for the review.
I've applied improvements mentioned in your comments and PR is ready for another check.
