### PR TITLE
Use raw non-breaking space for an empty `iframe`'s `title`

### LINKED ISSUE #5189: Failing test: `tests/core/creators/aria`
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Run test on IE11

### Expected result

*What is the expected result of the above steps?*

Test is passing.

### Actual result

*What is the actual result of the above steps?*

Test fails with: 

Editor's title label is incorrect
Expected: &nbsp; (string)
Actual: &amp;nbsp; (string)

## Other details

* Browser: IE11
* OS: Win10
* CKEditor version: 4.19.0 (pre release)
* Installed CKEditor plugins: development

### PR DESCRIPTION
**Pull request by Comandeer**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

N/A

## What changes did you make?

Instead of using `&nbsp;` entity I've used a raw character for setting `iframe`'s `title` when there is no editor label.

## Which issues does your PR resolve?

Closes #5189.

### CODE REVIEW

File: plugins/wysiwygarea/plugin.js [hunk 1]
```diff
@@ -416,7 +416,8 @@
 				CKEDITOR.tools.setTimeout( onDomReady, 0, this, win );
 			}, this );
 
-			this._.docTitle = this.getWindow().getFrame().getAttribute( 'title' ) || '&nbsp;';
+			// In case of lack of the title attribute, use non-breaking space.
+			this._.docTitle = this.getWindow().getFrame().getAttribute( 'title' ) || '\xa0';
```
Comment (sculpt0r) [inline plugins/wysiwygarea/plugin.js:420]: I tried this with '&NonBreakingSpace;' but there is a problem with the initial `&` in the HTML entity representation. So it appears that the representation is the issue, not the 'space' or 'non-breaking space'? If you try it with `\xA0` the test also passes. Could you confirm? Additionally - could you decide whether a casual space is enough or the non-breaking one is needed? After that - please adjust the solution (and the test).

**Review by sculpt0r — CHANGES_REQUESTED** [review]
@Comandeer - I have one question about the solution (please take a look at the inline comment). Also there is additional comment about the comment 🙈

File: plugins/wysiwygarea/plugin.js (hunk 1 above)
Comment (Comandeer) [reply plugins/wysiwygarea/plugin.js:420]: I've added a comment.

The regular space can't be used here as it is treated by screen readers as no content, making them read the URL of the `iframe`.

**Comment by Comandeer** [comment]
I've updated comments in code and tests.

**Review by sculpt0r — APPROVED** [review]
Thank you for the corrects. The tests works on IE11, 10 & 8 👍 

Sorry for miscommunication in https://github.com/ckeditor/ckeditor4/pull/5193/files#r869940326
