### PR TITLE
API docs fixes

### LINKED ISSUE #4062: Invalid link formatting in "fileUploadResponse" event API docs
## Type of report

Docs

## Provide a description of requested docs changes

See https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-fileUploadResponse:

image

### LINKED ISSUE #4069: Broken links in generated docs
## Type of report

Docs

## Provide a description of requested docs changes

* https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html
  - Link: http://highlightjs.org/static/test.html
* https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog_definition_textarea.html
  - Link: http://unicode.org/cldr/utility/character.jsp?a=202A
  - Link: http://unicode.org/cldr/utility/character.jsp?a=202B

### PR DESCRIPTION
**Pull request by f1ames**
## What is the purpose of this pull request?

Docs

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

Not needed.

## What changes did you make?

I created one PR to fix two API docs issues since these changes are really small. As for outdated `unicode.org` links see https://github.com/ckeditor/ckeditor4/issues/4069#issuecomment-636868425.

## Which issues does your PR resolve?

Closes #4062.
Closes #4069.

### CODE REVIEW

File: plugins/dialog/dialogDefinition.js [hunk 1]
```diff
@@ -1053,8 +1053,8 @@
  *
  * If the direction was set, a marker will be prepended to every non-empty value of this input:
  *
- * * [`\u202A`](http://unicode.org/cldr/utility/character.jsp?a=202A) &ndash; for Right-To-Left,
- * * [`\u202B`](http://unicode.org/cldr/utility/character.jsp?a=202B) &ndash; for Left-To-Right.
+ * * [`\u202A`](https://www.unicode.org/charts/PDF/U2000.pdf) &ndash; for Right-To-Left,
+ * * [`\u202B`](https://www.unicode.org/charts/PDF/U2000.pdf) &ndash; for Left-To-Right.
```
Comment (Dumluregn) [inline plugins/dialog/dialogDefinition.js:1057]: PDF references aren't cool as they are not very specific (you still need to find the interesting part). But in this case I'm afraid we don't have a better option - I did find references on some different websites (like https://charbase.com/202a-unicode-left-to-right-embedding or https://www.fileformat.info/info/unicode/char/202a/index.htm), but none of them has any connection to Unicode so they may shut down any moment and we will run into the same issue again. Still, with the proposed solution we are vulnerable to the simple change of filename :see\_no\_evil: But let's hope Unicode forgets about this file and never changes it :smile:

**Comment by Dumluregn** [comment]
Travis is failing because of #4084.
