### PR TITLE
Fix incorrect HSL/HSLA conversion

### LINKED ISSUE #4597: Incorrect conversion of HSL/HSLA values
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open browser console.
2. Go to https://jsfiddle.net/7Ljwqmtz/1/
3. Check console.

### Expected result

Colors in the same console row should be the same.

### Actual result

Colors are different. The second parameter changed from `50%` to `0%`.

## Other details

* CKEditor version: 4.16.0

### PR DESCRIPTION
**Pull request by Comandeer**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4597](https://github.com/ckeditor/ckeditor4/issues/4597): Fixed: incorrect color conversion for HSL/HSLA values.
```

## What changes did you make?

Due to the issue mentioned in https://github.com/ckeditor/ckeditor4/issues/4597#issuecomment-823094637 I've introduced additional data saved for HSL colors (hue, saturation and lightness) alongside the concept of color type.

Additionally I added rounding of lightness value and fixed the issue with saturation being always 0 or 1, due to incorrect rounding.

## Which issues does your PR resolve?

Closes #4597.

Note: this PR is a bug fix, however it's targeted to `major` as already merged changes (#4599) introduced some tests that have incorrect values and this PR fixes it.

### CODE REVIEW

File: core/tools/color.js [hunk 1]
```diff
@@ -358,20 +417,21 @@
...
 				}
 
-				return [
-					hexToNumber( parts[ 1 ] + parts[ 2 ] ),
-					hexToNumber( parts[ 3 ] + parts[ 4 ] ),
-					hexToNumber( parts[ 5 ] + parts [ 6 ] ),
-					alpha
-				];
+				return {
+					type: CKEDITOR.tools.color.TYPE_RGB,
```
Comment (Dumluregn) [inline core/tools/color.js:421]: It looks a bit awkward that we return `TYPE_RGB` instead of `TYPE_HEX` here. I know that functionally it won't make any difference, but maybe we could distinguish them for clarity?

Comment (Dumluregn) [reply core/tools/color.js:421]: Unless it actually converts the hex color to RGB (and I guess it does) 🤔

File: tests/core/tools/color.js [hunk 2]
```diff
@@ -173,7 +167,56 @@
...
+
+			assert.areSame( CKEDITOR.tools.color.TYPE_RGB, color._.type, 'Color type is correctly set to RGB' );
+		},
+
+		// (#4597)
+		'test saving data about color type for hex color': function() {
+			var input = '#FF00FF',
+				color = new CKEDITOR.tools.color( input );
+
+			assert.areSame( CKEDITOR.tools.color.TYPE_RGB, color._.type, 'Color type is correctly set to RGB' );
```
Comment (Dumluregn) [inline tests/core/tools/color.js:218]: In these test we should also test channels (there are a lot of tests above but they are only testing the whole conversion, not the part with channel extraction like the `test saving data about color type, hue, saturation and ligthness for HSL color` test for HSL).

**Review by Dumluregn — CHANGES_REQUESTED** [review]
Just some small fixes needed here. I like the conversion of channels container from array to object 👍🏻

File: core/tools/color.js (hunk 1 above)
Comment (Comandeer) [reply core/tools/color.js:421]: Technically all colors are converted to RGB. However hex is only the other representation of RGB color, while HSL is a completely different color format. Because of that I've introduced only two types – RGB (for both representations, `rgb()` and hex ones) and HSL.

**Comment by Comandeer** [comment]
Ok, I've updated API docs and slightly modified tests to also assert channels.

File: core/tools/color.js (hunk 1 above)
Comment (Dumluregn) [reply core/tools/color.js:438]: Ok, makes sense.

**Comment by Dumluregn** [comment]
Rebased onto latest `major`.

**Review by Dumluregn — APPROVED** [review]
LGTM! 🎉 

I've only fixed tests error messages and added test case for hex code without `#`.
