### PR TITLE
Incorrect rendering of the color button on first opening

### LINKED ISSUE #4247: Incorrect rendering of the color button on first opening
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open manual test `tests/plugins/colorbutton/manual/customclasstext`.
2. Click "Text Color" button.

### Expected result

The color panel is rendered incorrectly:
The text Automatycznie is incorrectly positioned

### Actual result

The color panel should be rendered correctly.

## Other details

* CKEditor version: 4.7.0+ with Polish language
* Installed CKEditor plugins: colorbutton

### PR DESCRIPTION
**Pull request by KarolDawidziuk**
## What is the purpose of this pull request?

Bug fix 

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [x] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#<4247>](https://github.com/ckeditor/ckeditor4/issues/4247): Fixed: [Color Button](https://ckeditor.com/cke4/addon/colorbutton) Incorrect rendering of the color button on first opening.
```

## What changes did you make?

Removing scroll bar, that was cousing width calculation problem in the first render.

## Which issues does your PR resolve?

Closes #4247.

### CODE REVIEW

File: tests/plugins/colorbutton/colorbutton.js [hunk 1]
```diff
@@ -190,7 +190,29 @@
 		'test text color items not draggable': testElementsNotDraggable( 'TextColor' ),
 
 		// (#2430)
-		'test background color items not draggable': testElementsNotDraggable( 'BGColor' )
+		'test background color items not draggable': testElementsNotDraggable( 'BGColor' ),
+
+		// (#4247)
+		'test panel should not have a scrollbar': function() {
```
Comment (Comandeer) [inline tests/plugins/colorbutton/colorbutton.js:196]: In fact you check here if the `overflow: hidden` is applied correctly, not the scrollbar itself, so maybe:

```suggestion
		'test panel should have styles that prevent scrollbar appearance': function() {
```

**Review by Comandeer — CHANGES_REQUESTED** [review]
The fix itself looks good 👍🏻 However there are some issues with tests (see inline comments).

File: tests/plugins/colorbutton/manual/custompanelrender.md [hunk 2]
```diff
@@ -0,0 +1,13 @@
+@bender-tags: 4.16.1, bug, 4247
+@bender-ui: collapsed 
+@bender-ckeditor-plugins: wysiwygarea, toolbar, colorbutton, colordialog, sourcearea
+
+1. Click **Text Color** or **Background Color** button.
```
Comment (Comandeer) [inline tests/plugins/colorbutton/manual/custompanelrender.md:5]: Current procedure suggests that the test can be done only for the one button. But it's better to test both of the buttons. So I propose to make the first step (with expected and unexpected sections) for Text Color button and then the second step like:

```markdown
2. Repeat the procedure for the **Background Color** button.
```

**Review by Comandeer — CHANGES_REQUESTED** [review]
LGTM! I've got only one small remark about the description of manual test.

**Review by Comandeer — APPROVED** [review]
LGTM. I've just fixed some inconsistent indentation in manual test.

I'll wait with merging until `master` branch is unfrozen.
