### PR TITLE
Fix cell selection and navigation by TAB key after adding a new cell

### LINKED ISSUE #4904: Table cell selection and navigation by TAB key behaviour inconsistent after adding a new row
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create table with default parameters and fill each cell with some text
2. Right click on any cell and add a new row or column
3. Observe that the cell in which we clicked is selected
4. Press TAB

Please see the attached gif:

error

### Expected result

On pressing TAB selection should navigate to the next cell as it does when manually selecting a cell by Triple Clicking in it.

Behaviour when Triple Clicking on any cell and then pressing TAB key:

expected

### Actual result

Editor looses focus and the cell selection remains the same.

## Other details

* Browser: Google Chrome Version 94.0.4606.54 (Official Build) (64-bit)
* OS: Linux Mint 19.1
* CKEditor version: 4.14.1 - 4.17.0 (Standard)
* Installed CKEditor plugins: Standard Package

### PR DESCRIPTION
**Pull request by KarolDawidziuk**
## What is the purpose of this pull request?

Bug fix

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [x] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [x] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
* [#4904](https://github.com/ckeditor/ckeditor4/issues/4904): Fix cell selection and navigation by TAB key after adding a new cell.
```

## What changes did you make?

There was a problem with getting empty `td` element from selection by `new CKEDITOR.dom.elementPath()` method.

When the cell was empty, `CKEDITOR.dom.elementPath` didn't add `td` element to path elements, which caused in bypassing of all logic responsible for shifting focus and selection to the next cell.

The fix was pretty simple. 
I just change `CKEDITOR.dom.elementPath()` to `editor.elementsPath()` and removed the piece of code responsible for avoiding selecting empty cells.

## Which issues does your PR resolve?

Closes #4904.

### CODE REVIEW

File: plugins/tab/plugin.js [hunk 1]
```diff
@@ -65,9 +64,7 @@
 						} else if ( next ) {
 							next = new CKEDITOR.dom.element( next );
 							resultRange.moveToElementEditStart( next );
-							// Avoid selecting empty block makes the cursor blind.
-							if ( !( resultRange.checkStartOfBlock() && resultRange.checkEndOfBlock() ) )
```
Comment (Comandeer) [inline plugins/tab/plugin.js:69]: Is this change necessary? If it's added only to force our fake selection after pressing the <kbd>Tab</kbd> key, I'd remove it. It causes issues in Firefox and IE11 in editors without the `tableselection` plugin. After pressing the <kbd>Tab</kbd> key, the cursor disappears.

File: tests/plugins/tab/errorinlineeditor.js [hunk 2]
```diff
@@ -15,8 +15,6 @@
 			var editor = this.editor;
 
 			editor.focus();
-			var sel = editor.getSelection();
-			sel.removeAllRanges();
```
Comment (Comandeer) [inline tests/plugins/tab/errorinlineeditor.js:19]: This test does not seem to test anything sensible after this change – it basically just presses the <kbd>Tab</kbd> key now. Additionally, the unmodified version of the test raises the very same error described in [https://dev.ckeditor.com/ticket/17028](https://dev.ckeditor.com/ticket/17028) – which is the issue tested here. Could you check if the issue reappeared after your changes and think if you can come up with some sensible way to test it?

**Review by Comandeer — CHANGES_REQUESTED** [review]
The proposed fix resolves the issue, however it causes some problems in Firefox and IE11 (see my inline comments).

Additionally, some of your changes touch also editors without the `tableselection` plugin – could you prepare additional tests for such cases? Also, could you add unit tests?

File: plugins/tab/plugin.js (hunk 1 above)
Comment (KarolDawidziuk) [reply plugins/tab/plugin.js:69]: This change is not necessary. It was just my assumption with false selection. I did not realize that this was causing additional problems. So I will bring back the previous changes.

**Comment by KarolDawidziuk** [comment]
Thank you @Comandeer for the review.

I applied the improvements mentioned in your comments and PR is ready for another review.

Also, I found that there was a problem with getting proper `elementPath` when `startNode` was getting from `selection.getCommonAncestor()` I changed it for `selection.getStartElement()` and everything works well.

File: tests/plugins/tableselection/tablecellfocus.js [hunk 3]
```diff
@@ -0,0 +1,286 @@
+/* bender-tags: tableselection */
```
Comment (Comandeer) [inline tests/plugins/tableselection/tablecellfocus.js:1]: Tests in this file seem to pass also on the `master`. Could you check it?

File: tests/plugins/tableselection/tablecellfocus.js [hunk 4]
```diff
@@ -0,0 +1,286 @@
...
+				editable = editor.editable();
+
+			bot.setHtmlWithSelection( '<table border="1">' +
+				'<tbody>' +
+					'<tr>' +
+						'<td>1_1</td>' +
+						'<td>1_2</td>' +
+					'</tr>' +
+					'<tr>' +
+						'<td>success!^</td>' +
```
Comment (Comandeer) [inline tests/plugins/tableselection/tablecellfocus.js:259]: Probably it could be caused by the fact that you use a collapsed selection which is probably translated to the native one, not our `tableselection` one. To activate the latter you'd need to select the whole cell.

**Review by Comandeer — CHANGES_REQUESTED** [review]
The fix looks good, but there is an issue with the unit test (see my inline comment). Additionally, could you add tests for native selection? The change you introduced is also affecting the native one as well.

File: tests/plugins/tableselection/tablecellfocus.js (hunk 3 above)
Comment (KarolDawidziuk) [reply tests/plugins/tableselection/tablecellfocus.js:1]: Fixed.

File: tests/plugins/tableselection/tablecellfocus.js (hunk 4 above)
Comment (KarolDawidziuk) [reply tests/plugins/tableselection/tablecellfocus.js]: The collapsed selection was not causing the problem because there was a problem with moving focus, not operations on the table. Already fixed.

**Review by Comandeer — CHANGES_REQUESTED** [review]
As we spoke yesterday, could you split the unit tests and place all tests in the appropriate directory (`tab` plugin one).

**Comment by KarolDawidziuk** [comment]
Thank you @Comandeer for the review.

I split and moved tests to the `tab` plugin and PR is ready for another review.

**Review by Comandeer — CHANGES_REQUESTED** [review]
Everything looks fine. However, there is some issue with `tests/plugins/tab/tablefocus` test in IE8-10 – the first test always passes and there is info about some uncaught exception (probably it's connected with non-functioning `bender.tools.ignoreUnsupportedEnvironment()`). Could you take a look?

**Comment by KarolDawidziuk** [comment]
> Everything looks fine. However, there is some issue with tests/plugins/tab/tablefocus test in IE8-10 – the first test always passes and there is info about some uncaught exception (probably it's connected with non-functioning bender.tools.ignoreUnsupportedEnvironment()). Could you take a look?

The reason for this was simple. I forgot to add the `tableselection` plugin in the test header. Everything looks fine after that.

**Review by Comandeer — APPROVED** [review]
LGTM!
